FROM ubuntu:${UBUNTU_VERSION} as base

USER root

RUN apt-get update && apt-get install -y curl

# See http://bugs.python.org/issue19846
ENV LANG C.UTF-8

RUN apt-get update && apt-get install -y python3 python3-pip

RUN python3 -m pip install --upgrade pip setuptools

RUN ln -s $(which python3) /usr/local/bin/python

RUN pip install tensorflow==2.0

RUN apt-get autoremove -y && apt-get remove -y wget

WORKDIR /tf

EXPOSE 8888

RUN pip install flask

RUN pip install flask_restful

RUN pip install gsutil

RUN pip install -U sentence-transformers

RUN pip install pytorch

RUN mkdir /nlp_eval

COPY temp /root/.boto

COPY . /nlp_eval/


RUN cd /nlp_eval

#RUN python /nlp_eval/restapi.py

CMD  ["bash"]